### ISSUE TITLE
handling with many targets

### ISSUE THREAD

**Issue by alessandro-icabbi** [hjanuschka/fastlane-plugin-update_project_codesigning#5]
I have a project with many targets and one code base . When I update one target with code sign,  all the targets stays with the same code sign . Is there a way to manage this , something like : 
update_project_codesigning(
          path: "demo-project/demo/demo.xcodeproj", 
          target:"MyTarget"
          use_automatic_signing: true)
?

**Comment by hjanuschka** [comment]
thx for the feedback - right now it is only supported to update all targets (as this was my original use-case). 
i ll have a look at this, once i got a bit of time for it, it shouldn't be that hard.

**Comment by hjanuschka** [comment]
@alessandro-icabbi this has been implemented with ef5a27aa48cdc56fea76253ce6dea258a0534049

use it like (targets is an array 👍 ):

```ruby
update_project_codesigning(
    path: "demo-project/demo/demo.xcodeproj",
    use_automatic_signing: false,
    targets: ["demo"]
)
```

**Comment by alessandro-icabbi** [comment]
Thanks for your reply @hjanuschka !
Tried to test now but I got the error : 

fastlane finished with errors

[!] Could not find option 'target' in the list of available options: path, use_automatic_signing, team_id

**Comment by hjanuschka** [comment]
have you upgrade the plugin? 
`gem update fastlane-plugin_update_project_codesigning`

also the param is called target*s*  not without *s*
