### ISSUE TITLE
Problems with adding the plugin

### ISSUE THREAD

**Issue by zooldk** [hjanuschka/fastlane-plugin-update_project_codesigning#6]
Hi,

I know that this might be a local environment problem and I am no ruby expert (sorry)- but here it goes anyways. I am using the latest fastlane(2.17.1).

I am using rvm to supply me the different ruby versions. Currently I am using 2.2.2:

$ rvm list

rvm rubies

 * ruby-2.1.1 [ missing bin/ruby ]
   ruby-2.1.2 [ missing bin/ruby ]
   ruby-2.1.8 [ missing bin/ruby ]
   ruby-2.2.0 [ x86_64 ]
=> ruby-2.2.2 [ x86_64 ]

When adding the plugin, it fails:

$ fastlane add_plugin update_project_codesigning
+--------------------------------------------+---------+----------------------------+
|                                   Used plugins                                    |
+--------------------------------------------+---------+----------------------------+
| Plugin                                     | Version | Action                     |
+--------------------------------------------+---------+----------------------------+
| fastlane-plugin-cordova                    | 0.1.4   | cordova                    |
| fastlane-plugin-update_project_codesigning | 0.1.9   | update_project_codesigning |
+--------------------------------------------+---------+----------------------------+

[12:08:08]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/slarsen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-1.8.6/ext/json/ext/generator
/Users/slarsen/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170221-16601-1uibdlp.rb extconf.rb 
creating Makefile

current directory: /Users/slarsen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-1.8.6/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/slarsen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-1.8.6/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from /Users/slarsen/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/slarsen/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/slarsen/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Any ideas?

**Comment by zooldk** [comment]
Ok got it installed by using 'bundle package'. Sorry prob. n00b mistake!

**Comment by hjanuschka** [comment]
awesome - glad you got it working 🚀
